datorama/app-components

- app/src/components/base/Select/Select.types.js
it is just I need to show some icons in options, so this fix is very welcome :) looks like it does not break nothing, so it is just a good addition
> improve prop types for <Select />

- app/src/App.js
- app/src/components/base/Select/Select.js
- app/src/components/base/Select/SelectMenu.js
- app/src/components/base/Select/SelectOptions.js
- app/src/meta.json
- package-lock.json
- package.json
Added `toggleOpen` callback to the Select option renderer.
> Custom search option

- .circleci/config.yml
- app/package-lock.json
- app/package.json
- app/src/__tests__/Button.test.js
- app/src/components/base/Table.js
created a new pr. same as the old one.
> add circle ci and a small test

- app/src/docs/Theme.doc.js
> DAT-61908 Fix rendering issue

- package-lock.json
- package.json
- src/packages/core/Stepper/Stepper.tsx
- src/packages/core/Stepper/StepperBullet.tsx
- src/stories/core/Stepper.stories.tsx
- tsconfig.json
Refactor Collapse for TS + Add eslint/prettier configs
> Feature | DAT-64983: Collapse TS refactor

- .storybook/preview.js
- src/common/utils.ts
- src/packages/core/Button.tsx
- src/packages/core/Collapse/Collapse.tsx
- src/packages/core/Collapse/Collapsible.tsx
- src/packages/core/Icons/ArrowDown.tsx
- src/packages/core/Progress/Progress.tsx
- src/packages/core/Progress/RadialProgress.tsx
- src/packages/core/Tabs.tsx
- src/stories/core/Button.stories.tsx
- src/stories/core/Card.stories.tsx
- src/stories/core/Collapse.stories.tsx
- src/stories/core/Collapsible.stories.tsx
- src/stories/core/Modal.stories.tsx
- src/stories/core/Progress.stories.tsx
- src/stories/core/RadialProgress.stories.tsx
- src/stories/core/SegmentedButton.stories.tsx
- src/stories/core/Stepper.stories.tsx
- src/stories/core/Tabs.stories.tsx
> Feature | DAT-64983: Refactor Progress & RadialProgress with TS & storybook

- app/src/App.js
- app/src/components/utils.js
- app/src/meta.json
- dist/index.js
- package-lock.json
- package.json
> DAT-69160 fix dark mode

- .eslintrc
- package.json
- src/components/WidgetOverlay/WidgetOverlayInner.tsx
release package - version 1.0.0
> DAT-67527 release package

- README.md
- package-lock.json
- package.json
- rollup.config.js
- src/stories/1_GettingStarted.stories.mdx
This is a fix to the old script as well. instead of having a dist folder in the package it will be flat.
> DAT-67527 Add publish script

- README.md
- package-lock.json
- package.json
- src/components/BasicLine/Area.tsx
- src/components/BasicLine/BasicLine.tsx
- src/components/BasicLine/ChartTooltip.tsx
- src/components/BasicLine/Interaction.tsx
- src/components/BasicLine/Line.tsx
- src/components/BasicLine/charts.utils.ts
- src/stories/0_Notes.stories.mdx
- src/stories/BasicLine.stories.tsx
A basic line chart with colored area.
this line chart is for the search app. it is meant to be simple - without a brush or axis.
d3-scale - a utility for scaling numbers.
> DAT-70409 Line chart

- README.md
- package-lock.json
- package.json
- src/index.ts
- src/stories/0_Notes.stories.mdx
expose basic line component. a fix.
> DAT-70409 Expose basic line (package published)

- package-lock.json
- package.json
- src/components/Grid/Body.tsx
- src/components/Grid/Grid.tsx
- src/components/Grid/Grid.types.ts
- src/components/Grid/Header/Header.tsx
- src/components/Grid/Header/HeaderCol.tsx
- src/stories/0_Notes.stories.mdx
- implement controll columns width.
- add isResizable prop to control the resizable feature.
> DAT-71390 - app components add props to grid component

- package-lock.json
- package.json
- src/components/Grid/Body.tsx
- src/components/Grid/Grid.types.ts
- src/stories/0_Notes.stories.mdx
Add key prop to cellRenderer in Grid component
> DAT-71390 - add key to cellRenderer

- package-lock.json
- package.json
- src/components/BasicLine/BasicLine.tsx
- src/components/BasicLine/ChartTooltip.tsx
- src/components/BasicLine/Interaction.tsx
- src/stories/0_Notes.stories.mdx
For the BasicLine component - if the chart is close to the left edge of the screen - adjust the tooltip position.
> DAT-71893 search app or trending tooltip cropped

- src/components/BasicLine/BasicLine.tsx
- src/components/BasicLine/Interaction.tsx
> DAT-71893 fix types

- package-lock.json
- package.json
- src/components/Grid/Grid.tsx
- src/stories/0_Notes.stories.mdx
Fix Tokenization to support special characters in fuzzy search.
> DAT-72565 app components fix tokenization of fuzzy search

- package-lock.json
- package.json
- src/components/Grid/Body.tsx
- src/components/Grid/Grid.types.ts
- src/stories/0_Notes.stories.mdx
Write here a short description
> DAT-72188 table design changes

- .storybook/main.js
- .storybook/preview.js
- package-lock.json
- package.json
- rollup.config.js
- src/components/Asset.tsx
- src/index.ts
- src/stories/0_Notes.stories.mdx
- src/stories/Asset.stories.tsx
- src/types/undeclared-types.d.ts
changes Rollup loaders config - to load images like create react app.
added a new Asset component to load common images.
dev dep. @rollup/svgr
> DAT-73153 widget states

- package-lock.json
- package.json
- src/components/Datepicker/Datepicker.js
- src/stories/0_Notes.stories.mdx
Add class names to DatePicker's dropdown elements
> Feature | DAT-73496: DatePicker classnames

- package-lock.json
- package.json
- src/components/GridLayout/GridItem.tsx
- src/components/GridLayout/GridLayout.tsx
- src/stories/0_Notes.stories.mdx
- src/stories/Layout.stories.tsx
Updated breakpoints. simplified the component props - aligned with the design team.
> DAT-73991 update grid sizes

- package.json
- src/components/Datepicker/Datepicker.js
- src/stories/0_Notes.stories.mdx
Add an optional `headerRenderer` prop in DatePIcker component
> Feature | DAT-71968: DatePicker `headerRenderer`

- package-lock.json
- package.json
- src/components/Grid/Grid.types.ts
- src/components/Grid/Header/HeaderCol.tsx
- Add index and dataKey to headerCellRenderer in Grid component
- Bumped version patch and pushed the latest tag
> DAT-74631-add-a-tooltip-to-leads-and-qualified-leads-table-header

- package-lock.json
- package.json
- src/components/Grid/Body.tsx
- src/components/Grid/Grid.tsx
- src/stories/0_Notes.stories.mdx
add on row click prop to the grid
> DAT-75119 grid

- package-lock.json
- package.json
- src/components/Popover/index.tsx
- src/hooks/confirmation-modal.hooks.tsx
- src/index.ts
- src/stories/0_Notes.stories.mdx
- src/stories/ConfirmationModal.stories.mdx
- src/stories/ConfirmationModalPreview.tsx
- src/stories/Notifications.stories.mdx
- Added 'useConfirmationModal' utility hook + story & preview
> Feature | DAT-74753: Confirmation modal utility hook

- package-lock.json
- package.json
- src/components/Popover/index.tsx
- src/components/Popover/popover.hooks.ts
- src/stories/0_Notes.stories.mdx
Fix circular dependency with ClcikOut imported from src/index
> DAT-75435: Fix circular dependency

- package-lock.json
- package.json
- src/components/Grid/Body.tsx
- src/components/Grid/Grid.tsx
- src/components/Grid/Header/Header.tsx
- src/hooks/next.common.hooks.ts
Support column resize even when initial-set-column-widths are provided.
> DAT-69304 data dictionary app allow the user to make the expression column wider

- package-lock.json
- package.json
- src/components/Datepicker/Datepicker.js
- src/stories/0_Notes.stories.mdx
- src/stories/Datepicker.stories.tsx
Add placeholder support to the date picker component. it's optional. 
if a placeholder is passed and the date range is empty - show the placeholder.
> DAT-71970 me or install or add placeholder to datepicker

- package-lock.json
- package.json
- src/components/Popover/index.tsx
- src/components/Popover/popover.hooks.ts
- src/stories/0_Notes.stories.mdx
Wront type for trigger ref was given, changed it from `SVGAELEMENT` to `SVGSVGELEMENT`
> DAT-75924-fix type of trigger ref

- package-lock.json
- package.json
- src/components/Popover/index.tsx
- src/components/Popover/popover.hooks.ts
- src/stories/0_Notes.stories.mdx
> DAT-75931-Fix clickout logic

- package-lock.json
- package.json
- src/components/Select/InlineSearch.js
- src/stories/Select.stories.tsx
bug fix for select (hide placeholder when tags are displayed).
> DAT-72257 fix

- package-lock.json
- package.json
- src/components/TextInput.js
- src/stories/0_Notes.stories.mdx
> DAT-78455-Add onblur to text input

- package-lock.json
- package.json
- src/components/AppThemeProvider/AppThemeProvider.utils.ts
- src/stories/0_Notes.stories.mdx
- src/types/theme.types.ts
fixed circular dependencies and TS issue
> DAT-78614 fix circular dependencies and ts issues

- package-lock.json
- package.json
- src/components/TextInput.js
- src/stories/0_Notes.stories.mdx
> DAT-78759 text input maxlength

- package-lock.json
- package.json
- src/components/Select/SelectMenu.js
- src/stories/0_Notes.stories.mdx
select reposition portal on resize
> DAT-78933 select reposition portal on resize

- package-lock.json
- package.json
- src/components/Select/SelectMenu.js
- src/stories/0_Notes.stories.mdx
> DAT-78969 select portal dynamic width

- package-lock.json
- package.json
- src/components/Select/SelectMenu.js
- src/stories/0_Notes.stories.mdx
> DAT-79040 select portal closed on click

- package-lock.json
- package.json
- src/components/Select/Select.js
- src/components/Select/SelectHeader.js
- src/stories/0_Notes.stories.mdx
remove selection ability by using `isSingleOptionRemovable` flag
> DAT-79160 select remove selection ability

- package-lock.json
- package.json
- src/components/Search.tsx
- src/index.ts
- src/stories/0_Notes.stories.mdx
- src/stories/Search.stories.tsx
> DAT-79919 export search

- package-lock.json
- package.json
- src/components/Search.tsx
- src/stories/0_Notes.stories.mdx
Fixed import in search component
> DAT-79919-Fix asset import in search

- package-lock.json
- package.json
- src/components/Search/SearchInput.tsx
- src/index.ts
- src/stories/0_Notes.stories.mdx
- src/stories/SearchInput.stories.tsx
> DAT-80188-Improve search component

- .eslintrc
- package-lock.json
- package.json
- src/components/Select/Select.js
- src/components/Select/SelectMenu.js
- src/components/Select/SelectOptions.js
- src/stories/0_Notes.stories.mdx
Optional "rowHeight" prop for Select's options
> Feature | DAT-80055: Optional "rowHeight" prop for Select's options

- package-lock.json
- package.json
Having troubles with 2.8.0 version, trying to re-publish a new one
> Fix | DAT-82407: Bump to 2.8.1 to publish a new package

- package-lock.json
- package.json
- src/components/Range/index.tsx
- src/components/Range/range.hooks.ts
- src/stories/0_Notes.stories.mdx
> DAT-82407 range type input

- package-lock.json
- package.json
- src/components/Range/index.tsx
Fixed issue when clicked input and it triggered value change.
```
CTC Output:
Case approved, merging is possible.
The case is available at: https://gus.lightning.force.com/lightning/r/Case/500AH000001FkCuYAK/view
Updated at Wed Jun 16 06:45:16 UTC 2021
```
> W-9468806 disable drag on input click

- package-lock.json
- package.json
- src/components/ButtonGroup/ButtonGroup.tsx
- src/stories/0_Notes.stories.mdx
- src/stories/ButtonGroup.stories.tsx
- src/utils/theme.utils.js
https://user-images.githubusercontent.com/8877864/121525296-d3f82d80-ca00-11eb-86d3-f3e712c32b1b.mov
> Feature | DAT-79145: Button Group component

- .ops/pipelines/cr.groovy
- .pipelines/cr.groovy
Write here a short description
```
CTC Output:
Case approved, merging is possible.
The case is available at: https://gus.lightning.force.com/lightning/r/Case/500AH000001RYa1YAG/view
Updated at Tue Jul 13 14:30:57 UTC 2021
```
> W-9429373 move cr.groovy

- package.json
- src/components/TextInput.js
TextInput - added autofocus to propTypes
```
CTC Output:
Case approved, merging is possible.
The case is available at: https://gus.lightning.force.com/lightning/r/Case/500AH000001RY5wYAG/view
Updated at Wed Jul 14 07:36:42 UTC 2021
```
> W-9595441 - TextInput - added autofocus to propTypes

- package-lock.json
Update version in package-lock.json
```
CTC Output:
Case approved, merging is possible.
The case is available at: https://gus.lightning.force.com/lightning/r/Case/500AH000001RY5wYAG/view
Updated at Wed Jul 14 08:09:13 UTC 2021
```
> W-9595441 - Update version in package-lock.json
